{% set name = "blis" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flame/blis/archive/{{ version }}.tar.gz
  sha256: 76b22f29b7789cf117c0873d2a6b2a6d61f903869168148f2e7306353c105c37

build:
  number: 1
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - clangxx                # [win or osx]
    - llvm-tools             # [win or osx]
    - autotools_clang_conda  # [win]
    - m2-sed                 # [win]
    - sed                    # [unix]
    - perl
    - python >=3.5
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libblis.a                       # [unix]
    - test -f $PREFIX/lib/libblis${SHLIB_EXT}             # [unix]
    - test -f $PREFIX/include/blis/blis.h                 # [unix]
    - test -f $PREFIX/include/blis/cblas.h                # [unix]
    - if not exist %LIBRARY_INC%\\blis\\blis.h exit 1     # [win]
    - if not exist %LIBRARY_INC%\\blis\\cblas.h exit 1    # [win]
    - if not exist %LIBRARY_BIN%\\libblis.3.dll exit 1    # [win]
    - if not exist %LIBRARY_LIB%\\blis.lib exit 1         # [win]
    - if not exist %LIBRARY_LIB%\\libblis.lib exit 1      # [win]

about:
  home: http://github.com/flame/blis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'BLAS-like Library Instantiation Software Framework'

extra:
  recipe-maintainers:
    - isuruf
