{% set version = "2.0" %}

package:
  name: blis
  version: {{ version }}

source:
  url: https://github.com/flame/blis/archive/{{ version }}.tar.gz
  sha256: 08bbebd77914a6d1a43874ae5ec2f54fe6a77cba745f2532df28361b0f1ad1b3

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - clangxx                # [win or osx]
    - llvm-tools             # [win or osx]
    - autotools_clang_conda  # [win]
    - m2-sed                 # [win]
    - sed                    # [unix]
    - make                   # [linux]
    - perl
    - python >=3.5
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libblis.a                       # [unix]
    - test -f $PREFIX/lib/libblis${SHLIB_EXT}             # [unix]
    - test -f $PREFIX/include/blis/blis.h                 # [unix]
    - test -f $PREFIX/include/blis/cblas.h                # [unix]
    - if not exist %LIBRARY_INC%\\blis\\blis.h exit 1     # [win]
    - if not exist %LIBRARY_INC%\\blis\\cblas.h exit 1    # [win]
    - if not exist %LIBRARY_BIN%\\libblis.4.dll exit 1    # [win]
    - if not exist %LIBRARY_LIB%\\blis.lib exit 1         # [win]
    - if not exist %LIBRARY_LIB%\\libblis.lib exit 1      # [win]

about:
  home: http://github.com/flame/blis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: BLAS-like Library Instantiation Software Framework

extra:
  recipe-maintainers:
    - isuruf
    - h-vetinari
    - gdonval
