{% set name = "blis" %}
{% set version = "0.8.1" %}
{% set build_number = 3 %}
{% set build_string = "{}_h{}_{}".format(threading, PKG_HASH, build_number) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flame/blis/archive/{{ version }}.tar.gz
  sha256: 729694128719801e82fae7b5f2489ab73e4a467f46271beff09588c9265a697b

build:
  number: {{ build_number }}
  skip: true  # [win and vc<14]
  string: {{ build_string }}
  script_env:
    - CPU_FAMILY=x86_64  # [x86_64]
    - CPU_FAMILY=arm64   # [arm64 or aarch64]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autotools_clang_conda  # [win]
    - m2-sed                 # [win]
    - sed                    # [unix]
    - perl
    - python
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libblis${SHLIB_EXT}             # [unix]
    - test -f $PREFIX/include/blis/blis.h                 # [unix]
    - test -f $PREFIX/include/blis/cblas.h                # [unix]
    - if not exist %LIBRARY_INC%\\blis\\blis.h exit 1     # [win]
    - if not exist %LIBRARY_INC%\\blis\\cblas.h exit 1    # [win]
    - if not exist %LIBRARY_BIN%\\libblis.3.dll exit 1    # [win]
    - if not exist %LIBRARY_LIB%\\blis.lib exit 1         # [win]
    - if not exist %LIBRARY_LIB%\\libblis.lib exit 1      # [win]

about:
  home: http://github.com/flame/blis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: BLAS-like Library Instantiation Software Framework

extra:
  recipe-maintainers:
    - isuruf
    - h-vetinari
    - gdonval
